# fly.toml app configuration file generated for allison-richardson on 2023-09-03T12:16:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "allison-richardson"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
